from Crypto.PublicKey import RSA

f = open("private.pem", "rb")
private_key = RSA.importKey(f.read())
f.close()
f = open("public.pem", "rb")
public_key = RSA.importKey(f.read())
f.close()
print("Public: {} \n Private: {} \nN={}\n".format(public_key.e, private_key.d, public_key.n))
message = "alamakota"
cipher=public_key.encrypt(message.encode("utf-8"), "")
f = open("damian_cipher.txt", "rb")
print(f.read())
cipher_openssl=f.read()
f.close()

f=open("damian_nowy.txt","wb")
f.write(public_key.encrypt(message.encode("utf-8"), "")[0])
f.close()
f=open("damian_nowszy.txt","wb")
f.write(private_key.decrypt(cipher[0]))
f.close()
f = open("damian_cipher.txt", "rb")
print(f.read())
f.close()